language: node_js
node_js:
  - "8"
env:
  - TEST_ENV=travis
addons:
  chrome: stable
install:
  - npm install
before_script:
  - gatsby build
  - gatsby serve & # start a Web server
  - sleep 3 # give Web server some time to bind to sockets, etc
script:
  - npm run test
  - npm run test:e2e
sudo: false
